// Generated by LiveScript 1.3.1
(function(){
  var less, delimit, cli, Red, Yellow, fs, ref$, SetConfig, PrintSucess, PrintFailure, Config, WithDir;
  less = require("less");
  delimit = function(it){
    return it.sep;
  }(
  require("path"));
  cli = require("cli-color");
  Red = cli.redBright;
  Yellow = cli.yellowBright;
  fs = require("GetRidOfError")(
  require("fs"));
  ref$ = require("GeneralDev"), SetConfig = ref$.SetConfig, PrintSucess = ref$.PrintSucess, PrintFailure = ref$.PrintFailure;
  Config = {
    InitialExt: "less",
    FinalExtention: "css",
    Compile: function(FileName){
      var ReadFilePath;
      ReadFilePath = Config.DirToSave + delimit + FileName + "." + Config.InitialExt;
      return fs.readFile(ReadFilePath, 'utf8', function(data){
        less.render(data, function(error, output){
          var CreatePath, WriteFilePath;
          if (error) {
            CreatePath = Yellow(Config.DirToSave + delimit) + Red(FileName + "." + Config.InitialExt);
            console.log(Red("Less Error " + CreatePath + Yellow(" Type:") + Red(error.type + Yellow(" Line:[") + Red(error.line) + Yellow(":" + error.column + "]"))));
            console.log(Red(error.extract));
          } else {
            WriteFilePath = Config.DirToSave + delimit + FileName + "." + Config.FinalExtention;
            fs.writeFile(WriteFilePath, output.css, function(){
              PrintSucess(FileName);
            });
          }
        });
      });
    }
  };
  WithDir = function(Init, watch, clean, DirToSave, DirToLook){
    var AutoBuild;
    Init == null && (Init = true);
    watch == null && (watch = true);
    clean == null && (clean = false);
    DirToSave == null && (DirToSave = process.cwd());
    DirToLook == null && (DirToLook = process.cwd());
    Config.DirToSave = DirToSave;
    Config.DirToLook = DirToLook;
    AutoBuild = SetConfig(Config);
    AutoBuild(Init, watch, clean);
  };
  module.exports = WithDir;
}).call(this);
